# Generated by Django 5.0.7 on 2024-08-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmationmodel',
            options={'verbose_name': 'Confirmation', 'verbose_name_plural': 'Confirmations'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='confirmationmodel',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='uuid',
        ),
        migrations.AlterModelTable(
            name='confirmationmodel',
            table='Confirmation',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='Users',
        ),
    ]
