# Generated by Django 5.0.7 on 2024-08-01 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limited_time', models.IntegerField()),
                ('limited_tasks', models.TextField()),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Task',
                'db_table': 'Tasks',
            },
        ),
        migrations.AlterModelOptions(
            name='challengemodel',
            options={'verbose_name': 'challenge', 'verbose_name_plural': 'challenges'},
        ),
        migrations.RenameField(
            model_name='challengemodel',
            old_name='daily_missions',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='challengemodel',
            old_name='uuid',
            new_name='secret_key',
        ),
        migrations.RemoveField(
            model_name='challengemodel',
            name='limited_time',
        ),
        migrations.RemoveField(
            model_name='challengemodel',
            name='missions',
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='goal',
            field=models.CharField(default='knowladge', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterModelTable(
            name='challengemodel',
            table='challenges',
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'Members',
            },
        ),
        migrations.DeleteModel(
            name='ActiveUserModel',
        ),
    ]
