# Generated by Django 5.0.7 on 2024-08-05 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_tasksmodel_alter_challengemodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksmodel',
            name='limited_time',
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='is_different',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='limited_time',
            field=models.IntegerField(default='5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='challenge',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='challenges.challengemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='days',
            field=models.CharField(default='15', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='membermodel',
            unique_together={('challenge', 'user')},
        ),
    ]
