# Generated by Django 5.0.7 on 2024-08-06 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_tasksmodel_limited_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='limited_tasks',
            new_name='tasks',
        ),
        migrations.RemoveField(
            model_name='membermodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='membermodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tasksmodel',
            name='days',
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='due_date',
            field=models.DateField(default='2024-08-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='challenges.challengemodel'),
        ),
    ]
