# Generated by Django 5.0.7 on 2024-08-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_rename_limited_tasks_tasksmodel_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='challenges.challengemodel'),
        ),
        migrations.AlterModelTable(
            name='membermodel',
            table='members',
        ),
        migrations.AlterModelTable(
            name='tasksmodel',
            table='tasks',
        ),
    ]
