# Generated by Django 5.0.7 on 2024-08-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_donetaskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donetaskmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_task', to='challenges.tasksmodel'),
        ),
        migrations.AlterModelTable(
            name='donetaskmodel',
            table='done_task',
        ),
    ]
