# Generated by Django 5.0.7 on 2024-08-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_alter_donetaskmodel_task_alter_donetaskmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='tasks',
            new_name='task',
        ),
    ]
